compito: compito.o grafi.o coda.o
	g++ -o compito compito.o grafi.o coda.o

compito.o: compito.cc node.h
	g++ -c compito.cc

grafi.o: grafi.cc grafi.h
	g++ -c grafi.cc

coda.o: coda.cc coda.h
	g++ -c coda.cc